config/routes.rb
AppDemo::Application.routes.draw do
  get "/" => "forum#index", :as => "questions"
  get "/nova-discussao" => "forum#new", :as => "new_question"
  get "/:id" => "forum#show", :as => "question"
  get "/:id/resposta" => "forum#reply", :as => "reply"
  post  "/" => "forum#create"
  put   "/:id" => "forum#update"
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def index
    @questions = Question.all
  end
  
  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
  end

  def update
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/views/forum/index.html.erb
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question)%></li>
  <% end %>
</ul>

<%= link_to "Nova discussão", new_question_path %>

app/views/forum/new.html.erb
<%= form_for @question do |f| -%>
  <p><%= f.label :name %><%= f.text_field :name %></p>
  <p><%= f.text_field :email %></p>
  <p><%= f.text_field :title %></p>
  <p><%= f.text_area :text %></p>
  <p><%= f.submit "Cadastrar" %></p>
<% end -%>

app/views/forum/show.html.erb
<h1><%= h @question.title %></h1>
<div id="question_text"><%= h @question.text %></div>

<%= link_to "Responder", reply_path(@question) %>

app/views/forum/update.html.erb
<h1>Forum#update</h1>
<p>Find me in app/views/forum/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery","jquery.validate","forum" %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>